# Generated by Django 6.0.4 on 2026-04-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
