# Generated by Django 6.0.4 on 2026-05-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_entry_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='appointment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
