# Generated by Django 6.0.4 on 2026-05-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auditlog_expand_actions_null_object'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.UniqueConstraint(condition=models.Q(('is_archived', False)), fields=('book_number',), name='uniq_active_book_number'),
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.UniqueConstraint(condition=models.Q(('is_archived', False)), fields=('book', 'entry_number'), name='uniq_active_entry_number_per_book'),
        ),
    ]
