# Generated by Django 6.0.4 on 2026-05-12 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_clientintake_workflowdraft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowdraft',
            name='identities',
        ),
        migrations.CreateModel(
            name='ClientIntakeParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('intake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='api.clientintake')),
            ],
        ),
        migrations.CreateModel(
            name='ClientIntakeIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=100)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identities', to='api.clientintakeparty')),
            ],
        ),
    ]
