# Generated by Django 6.0.4 on 2026-05-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_workflowdraft_identities_clientintakeparty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientintakeparty',
            name='id_number',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='clientintakeparty',
            name='id_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='ClientIntakeIdentity',
        ),
    ]
