# Generated by Codex on 2026-05-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_clientintakeparty_id_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowdraft',
            name='notarization_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
