# Generated by Codex on 2026-05-13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_workflowdraft_notarization_datetime'),
    ]

    operations = [
        migrations.AlterModelTable(name='user', table='tbl_user'),
        migrations.AlterModelTable(name='book', table='tbl_book'),
        migrations.AlterModelTable(name='page', table='tbl_page'),
        migrations.AlterModelTable(name='entry', table='tbl_entry'),
        migrations.AlterModelTable(name='clientintake', table='tbl_client_intake'),
        migrations.AlterModelTable(name='clientintakeparty', table='tbl_client_intake_party'),
        migrations.AlterModelTable(name='workflowdraft', table='tbl_workflow_draft'),
        migrations.AlterModelTable(name='party', table='tbl_party'),
        migrations.AlterModelTable(name='witness', table='tbl_witness'),
        migrations.AlterModelTable(name='identity', table='tbl_identity'),
        migrations.AlterModelTable(name='auditlog', table='tbl_audit_log'),
    ]
